"""
Builds a real Jupyter notebook (.ipynb) from an analysis result.
The notebook is fully runnable (re-executing regenerates every chart)
AND ships with the already-rendered chart images baked into the cell
outputs, so it looks complete the moment it's opened — no execution
required.
"""
import time
from pathlib import Path

import nbformat as nbf

from app.services.loader import loader_code_for


def _md(text: str):
    return nbf.v4.new_markdown_cell(text)


def _code_with_image(source: str, image_b64: str | None = None, exec_count: int = 1):
    cell = nbf.v4.new_code_cell(source)
    if image_b64:
        output = nbf.v4.new_output(
            output_type="display_data",
            data={"image/png": image_b64, "text/plain": ["<Figure>"]},
            metadata={},
        )
        cell["outputs"] = [output]
        cell["execution_count"] = exec_count
    return cell


def build_notebook(
    *,
    dataset_filename: str,
    file_ext: str,
    analysis: dict,
    dataset_title: str | None = None,
) -> nbf.NotebookNode:
    nb = nbf.v4.new_notebook()
    cells = []
    overview = analysis["overview"]
    title = dataset_title or dataset_filename

    # ---------- Title ----------
    cells.append(_md(
        f"# 📊 {title} — Automated Data Science Report\n\n"
        f"Generated by **InsightForge AI Copilot** — an automated EDA & notebook builder.\n\n"
        f"| Metric | Value |\n|---|---|\n"
        f"| Rows | {overview['rows']} |\n"
        f"| Columns | {overview['columns']} |\n"
        f"| Duplicate rows | {overview['duplicate_rows']} |\n"
        f"| Missing cells | {overview['missing_cells']} ({overview['missing_pct']}%) |\n"
        f"| Memory usage | {overview['memory_kb']} KB |\n"
    ))

    # ---------- Setup ----------
    cells.append(_md("## 1. Setup & Data Loading"))
    setup_src = (
        "import pandas as pd\n"
        "import numpy as np\n"
        "import matplotlib.pyplot as plt\n"
        "import seaborn as sns\n\n"
        "sns.set_theme(style=\"darkgrid\")\n"
        f"{loader_code_for(file_ext, dataset_filename)}\n"
        "df.head()"
    )
    cells.append(nbf.v4.new_code_cell(setup_src))

    # ---------- Overview ----------
    cells.append(_md("## 2. Dataset Overview"))
    cells.append(nbf.v4.new_code_cell(
        "print('Shape:', df.shape)\n"
        "df.info()"
    ))
    cells.append(nbf.v4.new_code_cell("df.describe(include='all').T"))
    cells.append(nbf.v4.new_code_cell(
        "missing = df.isna().sum()\n"
        "missing = missing[missing > 0].sort_values(ascending=False)\n"
        "print('Duplicate rows:', df.duplicated().sum())\n"
        "missing"
    ))

    # ---------- Key insights ----------
    insights_md = "## 3. Key Automated Insights\n\n" + "\n".join(f"- {note}" for note in analysis["insights"])
    cells.append(_md(insights_md))

    # ---------- Visualizations ----------
    cells.append(_md("## 4. Visual Exploration\nEach chart below was generated automatically. Re-run the cells to regenerate them from scratch."))

    numeric_cols = overview["numeric_columns"]
    categorical_cols = overview["categorical_columns"]
    exec_n = 1

    chart_lookup = {c["title"]: c["image"] for c in analysis["charts"]}

    if "Missing Values Overview" in chart_lookup:
        src = (
            "missing = df.isna().sum()\n"
            "missing = missing[missing > 0].sort_values(ascending=False).head(20)\n"
            "plt.figure(figsize=(8, max(3, 0.35*len(missing))))\n"
            "plt.barh(missing.index[::-1], missing.values[::-1], color='#22d3c4')\n"
            "plt.title('Missing Values by Column')\n"
            "plt.xlabel('Missing values')\n"
            "plt.show()"
        )
        cells.append(_code_with_image(src, chart_lookup["Missing Values Overview"], exec_n)); exec_n += 1

    if "Correlation Heatmap" in chart_lookup:
        src = (
            f"numeric_cols = {numeric_cols!r}\n"
            "corr = df[numeric_cols].corr(numeric_only=True)\n"
            "plt.figure(figsize=(max(5,0.6*len(numeric_cols)), max(4,0.6*len(numeric_cols))))\n"
            "sns.heatmap(corr, annot=len(numeric_cols)<=12, fmt='.2f', cmap='mako', center=0)\n"
            "plt.title('Correlation Heatmap')\n"
            "plt.show()"
        )
        cells.append(_code_with_image(src, chart_lookup["Correlation Heatmap"], exec_n)); exec_n += 1

    if "Outlier Overview" in chart_lookup:
        src = (
            f"numeric_cols = {numeric_cols[:8]!r}\n"
            "data = df[numeric_cols].copy()\n"
            "data = (data - data.mean()) / data.std(ddof=0).replace(0, 1)\n"
            "plt.figure(figsize=(max(6,1.1*len(numeric_cols)), 4))\n"
            "sns.boxplot(data=data)\n"
            "plt.title('Outlier Overview (standardized scale)')\n"
            "plt.xticks(rotation=30)\n"
            "plt.show()"
        )
        cells.append(_code_with_image(src, chart_lookup["Outlier Overview"], exec_n)); exec_n += 1

    for chart in analysis["charts"]:
        if chart["title"].startswith("Distribution of"):
            col = chart["title"].replace("Distribution of ", "")
            src = (
                f"col = {col!r}\n"
                "plt.figure(figsize=(5,3.5))\n"
                "plt.hist(df[col].dropna(), bins=30, color='#7c6cff', edgecolor='#12141c')\n"
                "plt.title(f'Distribution: {col}')\n"
                "plt.xlabel(col)\n"
                "plt.ylabel('Frequency')\n"
                "plt.show()"
            )
            cells.append(_code_with_image(src, chart["image"], exec_n)); exec_n += 1

    for chart in analysis["charts"]:
        if chart["title"].startswith("Top categories in"):
            col = chart["title"].replace("Top categories in ", "")
            src = (
                f"col = {col!r}\n"
                "counts = df[col].value_counts().head(15)\n"
                "plt.figure(figsize=(5.5,3.5))\n"
                "plt.barh(counts.index.astype(str)[::-1], counts.values[::-1], color='#ff6ec7')\n"
                "plt.title(f'Top categories: {col}')\n"
                "plt.xlabel('Count')\n"
                "plt.show()"
            )
            cells.append(_code_with_image(src, chart["image"], exec_n)); exec_n += 1

    # ---------- Cleaning suggestions ----------
    cells.append(_md(
        "## 5. Suggested Cleaning Steps\n\n"
        "The cell below applies a conservative, common-sense cleaning pass. "
        "Review before applying to your real pipeline."
    ))
    cells.append(nbf.v4.new_code_cell(
        "df_clean = df.copy()\n"
        "df_clean = df_clean.drop_duplicates()\n"
        "num_cols = df_clean.select_dtypes(include=np.number).columns\n"
        "cat_cols = df_clean.select_dtypes(include=['object', 'category']).columns\n"
        "df_clean[num_cols] = df_clean[num_cols].fillna(df_clean[num_cols].median())\n"
        "for c in cat_cols:\n"
        "    if df_clean[c].isna().any():\n"
        "        df_clean[c] = df_clean[c].fillna(df_clean[c].mode().iloc[0] if not df_clean[c].mode().empty else 'Unknown')\n"
        "print('Cleaned shape:', df_clean.shape)\n"
        "df_clean.head()"
    ))

    # ---------- Next steps ----------
    cells.append(_md(
        "## 6. Suggested Next Steps\n\n"
        "- Pick a target column and frame the problem (classification / regression).\n"
        "- Encode categorical variables (one-hot / target encoding) as needed.\n"
        "- Scale numeric features for distance-based models.\n"
        "- Try a baseline model (e.g. `RandomForestClassifier` / `RandomForestRegressor`) before tuning.\n"
        "- Use cross-validation to get a robust performance estimate.\n"
        "\n---\n*Report generated automatically by InsightForge AI Copilot.*"
    ))

    nb["cells"] = cells
    nb["metadata"] = {
        "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
        "language_info": {"name": "python", "version": "3.10"},
        "generated_by": "InsightForge AI Copilot",
        "generated_at": time.strftime("%Y-%m-%d %H:%M:%S"),
    }
    return nb


def save_notebook(nb: nbf.NotebookNode, out_path: Path) -> Path:
    out_path.parent.mkdir(parents=True, exist_ok=True)
    with open(out_path, "w", encoding="utf-8") as f:
        nbf.write(nb, f)
    return out_path
